PolandDelivery/Components/ServicesCompanyViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using PolandDelivery.Models;
using PolandDelivery.Models.DBModels;
using PolandDelivery.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PolandDelivery.Components
{
    public class ServicesCompanyViewComponent : ViewComponent
    {
        private readonly ApplicationContext _databaseContext;
        private readonly IOptions<AppSettings> _appSettings;

        public ServicesCompanyViewComponent(ApplicationContext databaseContext, IOptions<AppSettings> appSettings)
        {
            _databaseContext = databaseContext;
            _appSettings = appSettings;
        }

        public IViewComponentResult Invoke()
        {
            List<ServicesCompanyVCRequest> model = _databaseContext.Menus.Where(w => w.ForServicesBlock == true).Take(_appSettings.Value.bannersNumber).OrderBy(o => o.Sort).Select(s => new ServicesCompanyVCRequest()
            {
                whiteIconUrl = s.WhiteIconUrl,
                blackIconUrl = s.BlackIconUrl,
                name = s.Name,
                url = s.Url
            }).ToList();
            return View(model);
        }
    }
}

PolandDelivery/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using PolandDelivery.Interfaces;
using PolandDelivery.Models;
using PolandDelivery.Models.DBModels;
using PolandDelivery.Models.ViewModels;
using System.Collections.Generic;
using System.Diagnostics;

namespace PolandDelivery.Controllers
{
    public class HomeController : Controller
    {
        private readonly IOptions<AppSettings> _appSettings;
        private readonly INews _newsModel;
        private readonly IGenericPages _genericPagesModel;

        public HomeController(IOptions<AppSettings> appSettings, INews newsModel, IGenericPages genericPagesModel)
        {
            _appSettings = appSettings;
            _newsModel = newsModel;
            _genericPagesModel = genericPagesModel;
        }

        public IActionResult Index() => View(new HomePageModel()
        {
            news = _newsModel.GetSliderNews(_appSettings.Value.sliderNewsNumber),
            banners = _newsModel.GetBanners(_appSettings.Value.bannersNumber)
        });

        public IActionResult About() => View(_genericPagesModel.GetPageContent(8));

        public IActionResult Contacts() => View();

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() => View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });

        public IActionResult Page404() => View();

        public IActionResult NotAccess() => View();
    }
}

PolandDelivery/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using PolandDelivery.Interfaces;
using PolandDelivery.Models.ViewModels;

namespace PolandDelivery.Controllers
{
    public class NewsController : Controller
    {
        private readonly INews _model;

        public NewsController(INews model) => _model = model;

        public IActionResult Index(NewsRequest input) => View(_model.GetPageNews(input));
    }
}

PolandDelivery/Views/Home/About.cshtml
@model PolandDelivery.Models.ViewModels.GenericPagesResponse
@{
    ViewData["Title"] = Model.title;
}

<div>
    <section class="page-header page-header--about-company">
        <div class="page-header__inner">
            <h1 class="page-header__title">@Model.title</h1>
        </div>
    </section>

    <div class="crumbs">
        <div class="c-container">
            <div class="crumbs__inner">
                <a asp-action="Index" asp-controller="Home">Головна</a> / <span>@Model.title</span>
            </div>
        </div>
    </div>

    <section id="included__about-company-block">
        @await Html.PartialAsync("AboutCompany")
    </section>

    @Model.content

    <section id="included__services-company-block" class="section--white">
        @await Component.InvokeAsync("ServicesCompany")
    </section>

    <section id="included__contact-block">
        @await Html.PartialAsync("Contact")
    </section>
</div>

PolandDelivery/Views/Home/Contacts.cshtml
@{
    ViewData["Title"] = "Контакти Delivery International Poland";
}

<div>
    <div class="crumbs crumbs--no-heading section--white">
        <div class="c-container">
            <div class="crumbs__inner">
                <a href="index.html">Головна</a> / <span>Контакти</span>
            </div>
        </div>
    </div>

    <section class="section--white">
        <div class="c-container c-container--contacts-page">
            <div class="contacts-page">
                <h2 class="section-title">Контакти</h2>
                <div class="contacts-page__inner">

                    <!-- Ukraine -->

                    <div class="contacts-page__one-side">
                        <ul class="contacts-page__ul">
                            <li class="contacts-page__item">
                                <h3 class="contacts-page__sub-title">Представництво в Україні</h3>
                                <a class="contacts-page__name-company" href="https://www.delivery-international.com/" target="_blank">"Delivery-International"</a>
                            </li>

                            <li class="contacts-page__item">
                                <img class="contacts-page__icon" src="../../img/system/icon/phone-call-icon--gray.svg" alt="icon">
                                <a class="contacts-page__link" href="tel:+380675578874">+38(067)557-88-74</a>
                            </li>

                            <li class="contacts-page__item">
                                <img class="contacts-page__icon" src="../../img/system/icon/mail-icon--gray.svg" alt="icon">
                                <a class="contacts-page__link" href="mailto:office@delivery-auto.com.ua">office@delivery-auto.com.ua</a>
                            </li>

                            <li class="contacts-page__item">
                                <img class="contacts-page__icon" src="../../img/system/icon/point-icon--gray.svg" alt="icon">
                                <a class="contacts-page__link" target="_blank" href="https://goo.gl/maps/EpAer2bhjUU5B8Fg9">
                                    Україна 01024, м. Київ, <br>
                                    вул. Велика Васильківська 15/2
                                </a>
                            </li>
                        </ul>

                        <div class="contacts-page__map">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d20328.156837730916!2d30.521835371020273!3d50.44073549223763!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d4cefee7040109%3A0x8c77c4dd773d01c!2z0YPQuy4g0JHQvtC70YzRiNCw0Y8g0JLQsNGB0LjQu9GM0LrQvtCy0YHQutCw0Y8sIDE1LzIsINCa0LjQtdCyLCAwMjAwMA!5e0!3m2!1sru!2sua!4v1618832759360!5m2!1sru!2sua" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                        </div>
                    </div>

                    <!-- Poland -->

                    <div class="contacts-page__one-side">
                        <ul class="contacts-page__ul">
                            <li class="contacts-page__item">
                                <h3 class="contacts-page__sub-title">Представництво в Польщі</h3>
                                <a class="contacts-page__name-company" target="_blank">"Delivery International Poland"</a>
                            </li>

                            <li class="contacts-page__item">
                                <img class="contacts-page__icon" src="../../img/system/icon/phone-call-icon--gray.svg" alt="icon">
                                <a class="contacts-page__link" href="tel:+48735633869">+48 735 633 869</a>
                            </li>

                            <li class="contacts-page__item">
                                <img class="contacts-page__icon" src="../../img/system/icon/mail-icon--gray.svg" alt="icon">
                                <a class="contacts-page__link" href="mailto:office@deliveryip.pl">office@deliveryip.pl</a>
                            </li>

                            <li class="contacts-page__item">
                                <img class="contacts-page__icon" src="../../img/system/icon/point-icon--gray.svg" alt="icon">
                                <a class="contacts-page__link" target="_blank" href="https://goo.gl/maps/HHCMThKSQdPa511p9">
                                    мн. Яна Кіліньського No2, <br>
                                    Жешув, 35-005
                                </a>
                            </li>
                        </ul>

                        <div class="contacts-page__map">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2562.3623293890296!2d22.006461215716616!3d50.04204347942104!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473cfb1d45174c9b%3A0x96b4fbe040013dcc!2zUGxhYyBKYW5hIEtpbGnFhHNraWVnbyAyLCAzNS0wMDUgUnplc3rDs3csINCf0L7Qu9GM0YjQsA!5e0!3m2!1sru!2sua!4v1618834840952!5m2!1sru!2sua" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                        </div>
                    </div>

                    <div class="socials">
                        <h4 class="socials__title">Долучайтесь до наших груп у соціальних мережах</h4>
                        <ul class="socials__ul">
                            <li class="socials__item">
                                <a class="socials__link" href="#" target="_blank">
                                    <img src="../../img/system/icon/socials/socials__whatsapp.svg" alt="whatsapp">
                                </a>
                            </li>

                            <li class="socials__item">
                                <a class="socials__link" href="#" target="_blank">
                                    <img src="../../img/system/icon/socials/socials__wechat.svg" alt="wechat">
                                </a>
                            </li>

                            <li class="socials__item">
                                <a class="socials__link" href="#" target="_blank">
                                    <img src="../../img/system/icon/socials/socials__telegram.svg" alt="telegram">
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="included__contact-block">
        @await Html.PartialAsync("Contact")
    </section>
</div>

PolandDelivery/Views/Home/Index.cshtml
@model PolandDelivery.Models.ViewModels.HomePageModel
@{
    ViewData["Title"] = "Delivery International Poland";
    int i = 0;
}

<div>

    <!-- Блок Слайдер Баннеров -->
    <section>
        <!-- desctop -->
        <div class="main-slider" id="main-slider--desctop">
            @foreach (var banner in Model.banners)
            {
                i++;
                <div class="main-slider__link" href="in-dev.html">
                    <img class="main-slider__img for-desc" src="@banner.HeadImage" alt="banner">
                    <img class="main-slider__img for-mob" src="@banner.HeadImageMobile" alt="banner">
                    <div class="main-slider__info">
                        <a class="main-slider__info-link" href="@banner.Url" target="_blank">
                            <h2 class="main-slider__title">@banner.Title</h2>
                            <p class="main-slider__desc">@banner.Description</p>
                        </a>

                        <div class="main-slider__nav">
                            <button class="main-slider__arrow-prev"></button>
                            <div class="indicator">
                                <span class="indicator__active">@($"0{i}")</span>
                                <span class="indicator__all">/@($"0{Model.banners.Count()}")</span>
                            </div>
                            <button class="main-slider__arrow-next"></button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </section>
    
    <section id="included__about-company-block">
        @await Html.PartialAsync("AboutCompany")
    </section>

    <section id="included__services-company-block" class="section--white">
        @*await Html.PartialAsync("ServicesCompany")*@
        @await Component.InvokeAsync("ServicesCompany")
    </section>

    <section id="included__contact-block">
        @await Html.PartialAsync("Contact")
    </section>

    <section class="section--white">
        <div class="c-container">
            <div class="news-block">
                <h2 class="section-title">Новини компанії</h2>

                <ul class="news-block__ul">
                    @foreach (var iter in Model.news)
                    {
                        <li class="news-block__item">
                            <a href="@Url.Action("Index", "News")" class="news-block__link">
                                <div class="news-block__banner">
                                    <img src="@iter.Image" alt="news banner">
                                </div>

                                <div class="news-block__info">
                                    <div class="news-block__info-inner">
                                        <time class="news-block__time">@(iter.CreatedDate.ToString("dd.MM.yyyy"))</time>
                                        <h4 class="news-block__title">@iter.Title</h4>
                                        <p class="news-block__desc">
                                            @iter.ContentShort
                                        </p>
                                        <div class="news-block__btn">
                                            <div class="news-block__svg">
                                                <svg width="31" height="8" viewBox="0 0 31 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                    <path d="M30.3536 4.35355C30.5488 4.15829 30.5488 3.84171 30.3536 3.64645L27.1716 0.464466C26.9763 0.269204 26.6597 0.269204 26.4645 0.464466C26.2692 0.659728 26.2692 0.976311 26.4645 1.17157L29.2929 4L26.4645 6.82843C26.2692 7.02369 26.2692 7.34027 26.4645 7.53553C26.6597 7.7308 26.9763 7.7308 27.1716 7.53553L30.3536 4.35355ZM0 4.5H30V3.5H0V4.5Z" fill="white" />
                                                </svg>
                                            </div>
                                            <p class="news-block__btn-text">Дізнатися більше</p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                    }
                </ul>

                <a class="all-news-btn" href="@Url.Action("Index", "News")">
                    <svg width="31" height="8" viewBox="0 0 31 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M30.3536 4.35355C30.5488 4.15829 30.5488 3.84171 30.3536 3.64645L27.1716 0.464466C26.9763 0.269204 26.6597 0.269204 26.4645 0.464466C26.2692 0.659728 26.2692 0.976311 26.4645 1.17157L29.2929 4L26.4645 6.82843C26.2692 7.02369 26.2692 7.34027 26.4645 7.53553C26.6597 7.7308 26.9763 7.7308 27.1716 7.53553L30.3536 4.35355ZM0 4.5H30V3.5H0V4.5Z" fill="#3A566C" />
                    </svg>

                    <p class="all-news-btn__text">Всі новини компанії</p>
                </a>
            </div>
        </div>
    </section>
</div>

PolandDelivery/Views/Home/NotAccess.cshtml
@{
    ViewData["Title"] = "Помилка доступу";
}

<div class="c-container" style="color: #2F6088; font-size: 28px; text-align: center; margin-top: 10%;">
    У вас немає доступу до сторінки
</div>

PolandDelivery/Views/Home/Page404.cshtml
@{
    ViewData["Title"] = "Сторінка не знайдена";
}

<div class="c-container" style="color: #2F6088; font-size: 28px; text-align: center; margin-top: 10%;">
    Сторінка не знайдена
</div>