PolandDelivery/Components/FooterMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PolandDelivery.Interfaces;

namespace PolandDelivery.Components
{
    public class FooterMenuViewComponent : ViewComponent
    {
        private IMenu _model;

        public FooterMenuViewComponent(IMenu model) => _model = model;

        public IViewComponentResult Invoke() => View(_model.GetMenu());
    }
}

PolandDelivery/Controllers/FileManagerController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.StaticFiles;
using System.IO;

namespace PolandDelivery.Controllers
{
    public class FileManagerController : Controller
    {
        private readonly IWebHostEnvironment _appEnvironment;

        public FileManagerController(IWebHostEnvironment appEnvironment) => _appEnvironment = appEnvironment;

        public IActionResult Index() => View();

        public FileResult Download(string filename)
        {
            string path = Path.Combine(_appEnvironment.ContentRootPath, $"wwwroot/files/{filename}");
            FileStream fs = new FileStream(path, FileMode.Open);
            string fileType = string.Empty;
            new FileExtensionContentTypeProvider().TryGetContentType(filename, out fileType);
            return File(fs, fileType, filename);
        }
    }
}

PolandDelivery/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using PolandDelivery.Interfaces;
using PolandDelivery.Models.ViewModels;

namespace PolandDelivery.Controllers
{
    public class NewsController : Controller
    {
        private readonly INews _model;

        public NewsController(INews model) => _model = model;

        public IActionResult Index(NewsRequest input) => View(_model.GetPageNews(input));
    }
}

PolandDelivery/Controllers/UserFormsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PolandDelivery.Interfaces;
using PolandDelivery.Models.ViewModels;
using System.Linq;

namespace PolandDelivery.Controllers
{
    public class UserFormsController : Controller
    {
        private readonly IUserForms _model;
        private readonly ILogger<UserFormsController> _logger;

        public UserFormsController(ILogger<UserFormsController> logger, IUserForms model)
        {
            _model = model;
            _logger = logger;
        }

        [HttpPost]
        public JsonResult SendCallbackRequest(CallbackRequest input)
        {
            ApiResult result;
            if (ModelState.IsValid)
            {
                result = _model.SendCallbackRequest(input);
            }
            else
            {
                result = new ApiResult(ModelState.Values.SelectMany(v => v.Errors));
                _logger.LogError(result.message);
            }
            return Json(result);
        }

        [HttpPost]
        public JsonResult SendMailingRequest(MailingRequest input)
        {
            ApiResult result;
            if (ModelState.IsValid)
            {
                result = _model.SendMailingRequest(input);
            }
            else
            {
                result = new ApiResult(ModelState.Values.SelectMany(v => v.Errors));
                _logger.LogError(result.message);
            }
            return Json(result);
        }
    }
}

PolandDelivery/Views/Shared/AboutCompany.cshtml
<div class="c-container">
    <div class="about-company">
        <div class="about-company__info">
            <h2 class="section-title">Про компанію Delivery International Poland</h2>
            <div class="text-block">
                <p>Група компаній «DELIVERY» почала роботу в 2001 році. Основною спеціалізацією групи є надання транспортних та логістичних послуг для сектору В2В (суб’єкти підприємницької діяльності та корпоративний сектор) як на території України, так і за її межами.</p>
                <p>
                    За роки роботи наша група стала надійним партнером для більш ніж 500 тисяч корпоративних клієнтів, які працюють в усіх галузях економіки країни.
                </p>
            </div>
        </div>

        <div class="about-company__map">
            <img src="../img/system/any/world-map.svg" alt="world map">
        </div>
    </div>
</div>

PolandDelivery/Views/Shared/Contact.cshtml
<script src="https://unpkg.com/imask"></script>

<!-- <section> -->
<div class="c-container">
    <div class="contact">
        <div class="contact-info">
            <h2 class="section-title">Зв'язатися з нами</h2>
            <p>Залишіть заявку, щоб замовити перевезення або дізнатися більше про послуги компанії</p>
        </div>

        <div action="" class="contact-form">
            <div class="contact-form__line">
                <div class="contact-form__item label-rotate">
                    <input class="label-rotate__input" id="name-callback" name="name-callback" type="text" placeholder="Ваше ім’я">
                    <label for="name" class="label-rotate__label">Ваше ім’я</label>
                </div>
            </div>

            <div class="contact-form__line">
                <div class="contact-form__item--short label-rotate">
                    <input class="label-rotate__input" id="tel-number-callback" name="tel-number-callback" type="text" placeholder="Номер телефону">
                    <label for="tel-number" class="label-rotate__label">Номер телефону</label>
                </div>

                <div class="contact-form__item--short label-rotate">
                    <input class="label-rotate__input" id="email-callback" name="email-callback" type="text" placeholder="E-mail">
                    <label for="Email" class="label-rotate__label">E-mail</label>
                </div>
            </div>

            <div class="contact-form__line">
                <div class="contact-form__item label-rotate">
                    <textarea class="label-rotate__input" placeholder="Ваше повідомлення" id="message-callback" name="message-callback" required></textarea>
                    <label for="message" class="label-rotate__label">Ваше повідомлення</label>
                </div>
            </div>

            <p class="contact-form__notice">Надсилаючи повідомлення ви даєте згоду на <a href="#" target="_blank">обробку песональних данних.</a></p>

            <button class="main-btn popup-default_open" onclick="SendCallbackRequest()">Надіслати</button>
        </div>
    </div>
</div>
<!-- </section> -->

<script type="text/javascript">

    var phoneMask = IMask(
        document.getElementById('tel-number-callback'), {
        mask: '+{38}(000)000-00-00'
    });

    function SendCallbackRequest() {
        var _name = $("#name-callback").val();
        var _phone = $("#tel-number-callback").val();
        var _email = $("#email-callback").val();
        var _message = $("#message-callback").val();

        var data = {
            name: _name,
            email: _email,
            phone: _phone,
            message: _message
        };

        var url = '@Url.Action("SendCallbackRequest", "UserForms")';

        $.ajax({
            url: url,
            type: "POST",
            data: data,
            dataType: 'json',
            success: function (data) {
                if (data.state == true) {
                    show_message("Ваша заявка успішно відправлена!", "Наш менеджер зв’яжеться з Вами найближчим часом.", false);
                    $("#name-callback").val('');
                    $("#tel-number-callback").val('');
                    $("#email-callback").val('');
                    $("#message-callback").val('');
                }
                else {
                    show_message("Помилка даних", data.message, true);
                }
            },
            error: function (data) {
                show_message("Помилка серверу", data.responseText, true);
            }
        });
    }

</script>

PolandDelivery/Views/Shared/Footer.cshtml
<div class="c-container">
    <div class="footer__inner">
        <div class="footer-main">
            <div class="hot-line">
                <a class="hot-line__number" href="tel:380675578874">
                    <img src="../../img/system/icon/phone-call-icon.svg" alt="icon">
                    +38(067)557-88-74
                </a>

                <a class="hot-line__number" href="tel:48735633869">
                    <img src="../../img/system/icon/phone-call-icon.svg" alt="icon">
                    +48(735)63-38-69
                </a>

                <p class="hot-line__schedule">ПН-ПТ 08:00-18:00 СБ 09:00-15:00</p>
            </div>

            @await Component.InvokeAsync("FooterMenu")

            <div class="footer-nav">
                <div class="footer-mav__group-link">
                    <a class="footer-nav__title" asp-action="About" asp-controller="Home">Про компанію</a>
                    <a class="footer-nav__title" asp-action="Index" asp-controller="News">Новини</a>
                </div>

                <div class="subscription">
                    <h5 class="subscription__title">Підпишіться на E-mail розсилку компанії, щоб бути в курсі новин</h5>
                    <div class="subscription__form">
                        <input class="subscription__input" type="text" id="email-mailing" name="email-mailing" placeholder="E-mail">
                        <button class="main-btn popup-default_open" onclick="SendMailingRequest()">Підписатись</button>
                    </div>
                </div>

                <div>
                    <a class="footer-nav__link footer-nav__link--small" asp-action="Download" asp-controller="FileManager" asp-route-filename="Regulations.docx" target="_blank">Нормативно-правові акти</a>
                    <a class="footer-nav__link footer-nav__link--small" asp-action="Download" asp-controller="FileManager" asp-route-filename="PrivacyPolicy.txt" target="_blank">Політика конфіденційності</a>
                </div>
            </div>
        </div>

        <div class="footer-sub">
            <a asp-action="Index" asp-controller="Home" class="footer-sub__logo">
                <img src="../../img/system/logos/DI-logo--grey.png" alt="logo">
            </a>

            <div class="contacts-company contacts-company--poland">
                <p>DELIVERY INTERNATIONAL POLAND sp. z o.o.</p>
                <p>
                    <a href="https://goo.gl/maps/y3M1hGgR4j6Rs1Kz9" target="_blank">
                        pl. Jana Kilińskiego nr 2, <br>
                        Rzeszów, 35-005
                    </a>
                </p>
                <p>NIP: 5170406933 REGON: 386199471</p>
                <p><a href="mailto:office@deliveryip.pl">E-mail:office@deliveryip.pl</a></p>
            </div>

            <div class="contacts-company">
                <p>Група компаній «Делівері» © 2001-2021</p>
                <p>
                    <a href="https://goo.gl/maps/UxNcJ1RvpGVH7Ubk9" target="_blank">
                        Україна 01024, м. Київ, <br>
                        вул. Велика Васильківська 15/2
                    </a>
                </p>
                <p><a href="mailto:office@delivery-auto.com.ua">E-mail:office@delivery-auto.com.ua</a></p>
            </div>

            <div class="payments">
                <div class="payments__item">
                    <img src="../../img/system/logos/footer__visa.png" alt="visa">
                </div>

                <div class="payments__item">
                    <img src="../../img/system/logos/footer__mastercard.png" alt="mastercard">
                </div>
            </div>
        </div>
    </div>

    <script>
        $('#drop-down').on('click', function (event) {
            $('.footer-nav__drop-down').toggleClass('drop-down__active');
            $('#drop-down').toggleClass('drop-down__active-icon');
        });

        function SendMailingRequest() {
            var _email = $("#email-mailing").val();

            var data = {
                email: _email
            };

            var url = '@Url.Action("SendMailingRequest", "UserForms")';

            $.ajax({
                url: url,
                type: "POST",
                data: data,
                dataType: 'json',
                success: function (data) {
                    if (data.state == true) {
                        show_message("Ваша заявка успішно відправлена!", "Ви підписані на нашу розсилку.", false);
                        $("#email-mailing").val('');
                    }
                    else {
                        show_message("Помилка даних", data.message, true);
                    }
                },
                error: function (data) {
                    show_message("Помилка серверу", data.responseText, true);
                }
            });
        }
    </script>
</div>

PolandDelivery/Views/Shared/Header.cshtml
<div class="c-container">
    <nav class="header__inner">
        <a class="header__logo" asp-action="Index" asp-controller="Home">
            <img src="../../img/system/logos/DI-logo.png" alt="logo">
        </a>

        @await Component.InvokeAsync("HeaderMenu")
        
        <div style="color: white;">
            @if (User.Identity.IsAuthenticated)
            {
                <div>
                    @User.Identity.Name
                </div>
                <div>
                    <form method="post" asp-controller="Account" asp-action="Logout">
                        <input type="submit" style="text-decoration: underline; color: white; cursor: pointer; font-size: 16px;" value="Вийти" />
                    </form>
                </div>
            }
            else
            {
                <div>
                    <a asp-action="Login" asp-controller="Account">Увійти</a>
                </div>
            }
        </div>
        
        <div class="nav-menu__group">
            <div class="nav-hot-line">
                <a href="tel:+380675366070" class="nav-hot-line__number">
                    <img src="../../img/system/icon/phone-call-icon.svg" alt="icon">
                    <p>+38(067)536-60-70</p>
                </a>
                <p class="nav-hot-line__schedule">ПН-ПТ 08:00-18:00</p>
                <p class="nav-hot-line__schedule">СБ 09:00-15:00</p>
            </div>

            <div class="mob-menu-btn"></div>
        </div>
    </nav>

    <script>
        // При открытии меню ЛК -- закрывать Моб.меню
        $(".mob-menu-btn").on('click', function (e) {
            $(".mob-menu-btn").toggleClass("mob-menu-btn--opened");
            $(".nav-menu").toggleClass("nav-menu--active");
            $("#body").toggleClass("no-scroll");
        })
    </script>
</div>

PolandDelivery/Views/Shared/PopUp.cshtml
<!-- Pop Up Подписка на новости -->
<div id="popup-default" style="display: none;">
    <!-- Для поп-апа Ошибки - нужно добавлять класс <form class="popup-notify popup-notify--error"> -->
    <form id="popup-form" class="popup-notify">
        <div>
            <h3 class="popup-notify__title" id="popup-title"></h3>
            <p id="popup-message"></p>
        </div>
        <div class="popup-icon">
            <img src="../../img/system/icon/pop-up__notify-car-icon.png" alt="caricon">
        </div>
    </form>
</div>

<!-- необходим тут -->
<script src="../../js/components/popup.js" type="text/javascript"></script>

PolandDelivery/Views/Shared/ServicesCompany.cshtml
<div class="c-container">
    <div class="services-block">
        <div class="services-block__info">
            <h2 class="section-title">Послуги компанії</h2>
            <p>Запрошуємо вас скористатись нашими послугами. Впевнені, що ми зможемо вирішити будь яке ваше питання у логістичній сфері</p>
        </div>

        <ul class="services-block__ul">
            <li class="services-block__item">
                <a asp-action="Index" asp-controller="GenericPages" asp-route-id="4" target="_blank" class="services-block__link">
                    <div class="services-block__icon">
                        <img class="white-icon" src="../img/system/icon/services/services__truck.svg" alt="icon">
                        <img class="black-icon" src="../img/system/icon/services/services__truck--black.svg" alt="icon">
                    </div>
                    <p class="services-block__text">Комерційні перевезення</p>
                    <div class="services-block__open-icon">
                        <img class="white-icon" src="../img/system/icon/arrow-white.svg" alt="open-icon">
                        <img class="black-icon" src="../img/system/icon/arrow-black.svg" alt="open-icon">
                    </div>
                </a>
            </li>

            <li class="services-block__item">
                <a asp-action="Index" asp-controller="GenericPages" asp-route-id="5" target="_blank" class="services-block__link">
                    <div class="services-block__icon">
                        <img class="white-icon" src="../img/system/icon/services/services__box.svg" alt="icon">
                        <img class="black-icon" src="../img/system/icon/services/services__box--black.svg" alt="icon">
                    </div>
                    <p class="services-block__text">Складські послуги</p>
                    <div class="services-block__open-icon">
                        <img class="white-icon" src="../img/system/icon/arrow-white.svg" alt="open-icon">
                        <img class="black-icon" src="../img/system/icon/arrow-black.svg" alt="open-icon">
                    </div>
                </a>
            </li>

            <li class="services-block__item">
                <a asp-action="Index" asp-controller="GenericPages" asp-route-id="6" target="_blank" class="services-block__link">
                    <div class="services-block__icon">
                        <img class="white-icon" src="../img/system/icon/services/services__world.svg" alt="icon">
                        <img class="black-icon" src="../img/system/icon/services/services__world--black.svg" alt="icon">
                    </div>
                    <p class="services-block__text">Експортна пошта</p>
                    <div class="services-block__open-icon">
                        <img class="white-icon" src="../img/system/icon/arrow-white.svg" alt="open-icon">
                        <img class="black-icon" src="../img/system/icon/arrow-black.svg" alt="open-icon">
                    </div>
                </a>
            </li>

            <li class="services-block__item">
                <a asp-action="Index" asp-controller="GenericPages" asp-route-id="7" target="_blank" class="services-block__link">
                    <div class="services-block__icon">
                        <img class="white-icon" src="../img/system/icon/services/services__envelope.svg" alt="icon">
                        <img class="black-icon" src="../img/system/icon/services/services__envelope--black.svg" alt="icon">
                    </div>
                    <p class="services-block__text">Імпортна пошта</p>
                    <div class="services-block__open-icon">
                        <img class="white-icon" src="../img/system/icon/arrow-white.svg" alt="open-icon">
                        <img class="black-icon" src="../img/system/icon/arrow-black.svg" alt="open-icon">
                    </div>
                </a>
            </li>
        </ul>
    </div>
</div>

PolandDelivery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!-- ================================================
    Project:        Delivery International Poland
    Author:         Anton Shaposhnikov
    Telegram:       https://t.me/purrpurr
===================================================== -->
<html lang="uk">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <!-- Fonts -->
    <link href="../../fonts/SegoeUI/fonts.css" rel="stylesheet" type="text/css">
    <!-- PAGE LEVEL PLUGIN STYLES -->
    <link href="../../css/normalize.css" rel="stylesheet">
    <!-- Slick Slider -->
    <link href="../../css/components/slick.css" rel="stylesheet" type="text/css">
    <link href="../../css/components/slick-theme.css" rel="stylesheet" type="text/css">
    <!-- THEME STYLES -->
    <link href="../../css/common.css" rel="stylesheet" type="text/css" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="../../img/system/icon/favicon_international.ico" />
    <!-- ADD JQUERY HERE -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!-- Pop up JS -->
    <script src="https://cdn.jsdelivr.net/gh/vast-engineering/jquery-popup-overlay@2/jquery.popupoverlay.min.js"></script>
    <script src="../../js/components/popup.js" type="text/javascript"></script>
</head>

<body id="body">
    <main class="main">
        <header id="included__header" class="header">
            @await Html.PartialAsync("Header")
        </header>
        <!--========== Page Content ==========-->
        <div>
            @RenderBody()
        </div>
        <!--========== \Page Content ==========-->
    </main>

    <!--========== FOOTER LAYOUT ==========-->
    <footer id="included__footer" class="footer">
        @await Html.PartialAsync("Footer")
    </footer>
    <!--========== THE END FOOTER LAYOUT ==========-->
    <!-- Preloader -->
    <div class="preloader">
        <div class="preloader__row">
        </div>
    </div>
    <!-- Заглушка для IE -->
    <div class="for-ie">
        <div class="for-ie__title">УВАГА! Ви використовуєте застарілий браузер.</div>
        <p class="for-ie__desc">Щоб скористатися сайтом delivery-auto.com, рекомендуємо Вам оновити браузер до останньої версії або вибрати і встановити будь-який інший з запропонованих варіантів. Це безкоштовно і займе всього кілька хвилин.</p>
        <div class="for-ie__browsers">
            <a class="for-ie__item" href="https://www.google.com/intl/ru/chrome/">
                <img class="for-ie__icon" src="../../img/system/any/browser-icon-for-ie--chrome.svg" alt="Browser icon">
                <p class="for-ie__browser-name">Google Chrome</p>
            </a>

            <a class="for-ie__item" href="https://www.mozilla.org/ru/firefox/new/">
                <img class="for-ie__icon" src="../../img/system/any/browser-icon-for-ie--firefox.svg" alt="Browser icon">
                <p class="for-ie__browser-name">Mozilla Firefox</p>
            </a>

            <a class="for-ie__item" href="https://www.opera.com/ru">
                <img class="for-ie__icon" src="../../img/system/any/browser-icon-for-ie--opera.svg" alt="Browser icon">
                <p class="for-ie__browser-name">Opera Browser</p>
            </a>
        </div>
    </div>
    <!-- Pop-up html included -->
    <section id="included__pop-up">
        @await Html.PartialAsync("PopUp")
    </section>
    <!-- Slick Slider -->
    <script src="../../js/components/slick.min.js" type="text/javascript"></script>
    <script src="../../js/components/slick.main.js" type="text/javascript"></script>
    <!-- Details tag Pofyliff for Edge -->
    <script src="../../js/components/details-element-polyfill.js" type="text/javascript"></script>
    <!-- Main.js -->
    <script src="../../js/main.js" type="text/javascript"></script>
</body>
</html>